### ISSUE TITLE
Importerror on types.py

### ISSUE THREAD

**Issue by tmcquaig** [Lightning-AI/utilities#74]
## 🐛 Bug

`ImportError: cannot import name '_PATH' from 'pytorch_lightning.utilities.types' (C:\Users\tmcquaig\anaconda3\envs\Dreambooth-SD\lib\site-packages\pytorch_lightning\utilities\types.py)`

### To Reproduce

1. Installed Anaconda and https://github.com/JoePenna/Dreambooth-Stable-Diffusion
2. In the DreamBooth-SD environment created for in Ananconda, run "python main.py"

```
(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>python main.py
Traceback (most recent call last):
  File "E:\Dreambooth-Stable-Diffusion\main.py", line 2, in <module>
    from ldm.modules.pruningckptio import PruningCheckpointIO
  File "E:\Dreambooth-Stable-Diffusion\ldm\modules\pruningckptio.py", line 4, in <module>
    from pytorch_lightning.utilities.types import _PATH
ImportError: cannot import name '_PATH' from 'pytorch_lightning.utilities.types' (C:\Users\tmcquaig\anaconda3\envs\Dreambooth-SD\lib\site-packages\pytorch_lightning\utilities\types.py)

(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>pip show lightning-utilities
Name: lightning-utilities
Version: 0.4.2
Summary: PyTorch Lightning Sample project.
Home-page: https://github.com/Lightning-AI/utilities
Author: Lightning AI et al.
Author-email: pytorch@lightning.ai
License: Apache-2.0
Location: c:\users\tmcquaig\anaconda3\envs\dreambooth-sd\lib\site-packages
Requires:
Required-by: pytorch-lightning

(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>
```

#### Code sample

```
main.py", line 2, in <module>

`from` ldm.modules.pruningckptio import `PruningCheckpointIO`

pruningckptio.py", line 4, in <module>

`from` pytorch_lightning.utilities.types import `_PATH`
```

### Expected behavior

main.py should successfully run and Dreambooth Stable Diffusion should run :)

### Environment

```
(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>conda info

     active environment : Dreambooth-SD
    active env location : C:\Users\tmcquaig\anaconda3\envs\Dreambooth-SD
            shell level : 2
       user config file : C:\Users\tmcquaig\.condarc
 populated config files : C:\Users\tmcquaig\.condarc
          conda version : 22.11.1
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\Users\tmcquaig\anaconda3  (writable)
      conda av data dir : C:\Users\tmcquaig\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\tmcquaig\anaconda3\pkgs
                          C:\Users\tmcquaig\.conda\pkgs
                          C:\Users\tmcquaig\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\tmcquaig\anaconda3\envs
                          C:\Users\tmcquaig\.conda\envs
                          C:\Users\tmcquaig\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False


(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>

(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>pip list
Package             Version
------------------- -----------
aiohttp             3.8.3
aiosignal           1.3.1
async-timeout       4.0.2
attrs               22.1.0
certifi             2022.9.24
charset-normalizer  2.1.1
colorama            0.4.6
frozenlist          1.3.3
fsspec              2022.11.0
idna                3.4
lightning-utilities 0.4.2
multidict           6.0.3
numpy               1.23.5
packaging           22.0
pip                 22.3.1
protobuf            3.20.1
pytorch-lightning   1.8.4.post0
PyYAML              6.0
requests            2.28.1
setuptools          65.5.0
tensorboardX        2.5.1
torch               1.13.0
torchmetrics        0.11.0
tqdm                4.64.1
typing_extensions   4.4.0
urllib3             1.26.13
wheel               0.37.1
wincertstore        0.2
yarl                1.8.2

(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>

```

**Comment by tmcquaig** [comment]
Moving to https://github.com/Lightning-AI/lightning/issues/16036
